In [279]:
import pandas as pd

# Load the dataset
df = pd.read_csv('/Users/bhaskaradhikari/freelance/data/raw/bquxjob_423dc57a_18d43302074.csv')

In [284]:
df

,event_date,event_timestamp,event_name,event_params,event_previous_timestamp,event_value_in_usd,event_bundle_sequence_id,event_server_timestamp_offset,user_id,user_pseudo_id,...,geo,app_info,traffic_source,stream_id,platform,event_dimensions,ecommerce,items,collected_traffic_source,is_active_user
0,20240123,1706041021863308,page_view,"{\n ""event_params"": [{\n ""key"": ""batch_ord...",NaN,NaN,-1592486516,NaN,NaN,1.803115e+09,...,"{\n ""geo"": {\n ""city"": ""Columbia"",\n ""c...","{\n ""app_info"": null\n}","{\n ""traffic_source"": {\n ""name"": ""(direct...",2614673916,WEB,"{\n ""event_dimensions"": null\n}","{\n ""ecommerce"": null\n}","{\n ""items"": []\n}","{\n ""collected_traffic_source"": null\n}",True
1,20240123,1706043908464706,page_view,"{\n ""event_params"": [{\n ""key"": ""campaign""...",NaN,NaN,1294114882,NaN,NaN,1.370019e+09,...,"{\n ""geo"": {\n ""city"": ""Seattle"",\n ""co...","{\n ""app_info"": null\n}","{\n ""traffic_source"": {\n ""name"": ""(referr...",2614673916,WEB,"{\n ""event_dimensions"": null\n}","{\n ""ecommerce"": null\n}","{\n ""items"": []\n}","{\n ""collected_traffic_source"": {\n ""manua...",True
2,20240123,1706055327780748,page_view,"{\n ""event_params"": [{\n ""key"": ""source"",\...",NaN,NaN,-171470964,NaN,NaN,2.091432e+09,...,"{\n ""geo"": {\n ""city"": """",\n ""country"":...","{\n ""app_info"": null\n}","{\n ""traffic_source"": {\n ""name"": ""TNT_DPA...",2614673916,WEB,"{\n ""event_dimensions"": null\n}","{\n ""ecommerce"": null\n}","{\n ""items"": []\n}","{\n ""collected_traffic_source"": {\n ""manua...",True
3,20240123,1705989378681557,page_view,"{\n ""event_params"": [{\n ""key"": ""medium"",\...",NaN,NaN,-1696060715,NaN,NaN,1.821760e+09,...,"{\n ""geo"": {\n ""city"": ""Cypress"",\n ""co...","{\n ""app_info"": null\n}","{\n ""traffic_source"": {\n ""name"": ""TNT_Car...",2614673916,WEB,"{\n ""event_dimensions"": null\n}","{\n ""ecommerce"": null\n}","{\n ""items"": []\n}","{\n ""collected_traffic_source"": {\n ""manua...",True
4,20240123,1706013824763773,page_view,"{\n ""event_params"": [{\n ""key"": ""entrances...",NaN,NaN,1275185021,NaN,NaN,1.665243e+09,...,"{\n ""geo"": {\n ""city"": ""Lowell"",\n ""cou...","{\n ""app_info"": null\n}","{\n ""traffic_source"": {\n ""name"": ""TNT_Car...",2614673916,WEB,"{\n ""event_dimensions"": null\n}","{\n ""ecommerce"": null\n}","{\n ""items"": []\n}","{\n ""collected_traffic_source"": {\n ""manua...",True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,20240123,1706059367359036,page_view,"{\n ""event_params"": [{\n ""key"": ""page_loca...",NaN,NaN,-426859972,NaN,NaN,8.756038e+08,...,"{\n ""geo"": {\n ""city"": ""Midland"",\n ""co...","{\n ""app_info"": null\n}","{\n ""traffic_source"": {\n ""name"": ""TNT_Car...",2614673916,WEB,"{\n ""event_dimensions"": null\n}","{\n ""ecommerce"": null\n}","{\n ""items"": []\n}","{\n ""collected_traffic_source"": null\n}",True
996,20240123,1706059418688359,page_view,"{\n ""event_params"": [{\n ""key"": ""ignore_re...",NaN,NaN,-375530649,NaN,NaN,8.756038e+08,...,"{\n ""geo"": {\n ""city"": ""Midland"",\n ""co...","{\n ""app_info"": null\n}","{\n ""traffic_source"": {\n ""name"": ""TNT_Car...",2614673916,WEB,"{\n ""event_dimensions"": null\n}","{\n ""ecommerce"": null\n}","{\n ""items"": []\n}","{\n ""collected_traffic_source"": null\n}",True
997,20240123,1706059422947325,page_view,"{\n ""event_params"": [{\n ""key"": ""batch_pag...",NaN,NaN,-371271683,NaN,NaN,8.756038e+08,...,"{\n ""geo"": {\n ""city"": ""Midland"",\n ""co...","{\n ""app_info"": null\n}","{\n ""traffic_source"": {\n ""name"": ""TNT_Car...",2614673916,WEB,"{\n ""event_dimensions"": null\n}","{\n ""ecommerce"": null\n}","{\n ""items"": []\n}","{\n ""collected_traffic_source"": null\n}",True
998,20240123,1706059426919338,page_view,"{\n ""event_params"": [{\n ""key"": ""session_e...",NaN,NaN,-367299670,NaN,NaN,8.756038e+08,...,"{\n ""geo"": {\n ""city"": ""Midland"",\n ""co...","{\n ""app_info"": null\n}","{\n ""traffic_source"": {\n ""name"": ""TNT_Car...",2614673916,WEB,"{\n ""event_dimensions"": null\n}","{\n ""ecommerce"": null\n}","{\n ""items"": []\n}","{\n ""collected_traffic_source"": null\n}",True
999,20240123,1706059435947378,page_view,"{\n ""event_params"": [{\n ""key"": ""batch_pag...",NaN,NaN,-358271630,NaN,NaN,8.756038e+08,...,"{\n ""geo"": {\n ""city"": ""Midland"",\n ""co...","{\n ""app_info"": null\n}","{\n ""traffic_source"": {\n ""name"": ""TNT_Car...",2614673916,WEB,"{\n ""event_dimensions"": null\n}","{\n ""ecommerce"": null\n}","{\n ""items"": []\n}","{\n ""collected_traffic_source"": null\n}",True

In [263]:
column_names = list(df.columns.values)
column_names

['event_date',
 'event_timestamp',
 'event_name',
 'event_params',
 'event_previous_timestamp',
 'event_value_in_usd',
 'event_bundle_sequence_id',
 'event_server_timestamp_offset',
 'user_id',
 'user_pseudo_id',
 'privacy_info',
 'user_properties',
 'user_first_touch_timestamp',
 'user_ltv',
 'device',
 'geo',
 'app_info',
 'traffic_source',
 'stream_id',
 'platform',
 'event_dimensions',
 'ecommerce',
 'items',
 'collected_traffic_source',
 'is_active_user']

In [264]:
# To determine if there is enough data for geographical insights,
# we need to parse the 'geo' column and analyze the geographical distribution of events.

data=df

# Importing the necessary library for JSON manipulation
import json

# Defining a function to extract city and country information from the 'geo' column
def extract_geo_info(geo_json_str):
    try:
        # Parse the JSON string
        geo_json = json.loads(geo_json_str)
        # Extract city and country information
        city = geo_json["geo"]["city"]
        country = geo_json["geo"]["country"]
        return city, country
    except (KeyError, ValueError):
        # Return None values if parsing fails or keys are not found
        return None, None

# Apply the function to the 'geo' column and create a new DataFrame with city and country
geo_info = data['geo'].apply(lambda x: extract_geo_info(x))
geo_df = pd.DataFrame(geo_info.tolist(), columns=['City', 'Country'])


geo_df

         City        Country
0    Columbia  United States
1     Seattle  United States
2              United States
3     Cypress  United States
4      Lowell  United States
..        ...            ...
995   Midland  United States
996   Midland  United States
997   Midland  United States
998   Midland  United States
999   Midland  United States

[1000 rows x 2 columns]

In [265]:
# Assuming `df` is your DataFrame containing the listed attributes
primary_key_candidates = ['user_pseudo_id', 'event_timestamp', 'event_bundle_sequence_id']

for column in primary_key_candidates:
    unique_values = df[column].nunique()
    total_rows = len(df)
    null_values = df[column].isnull().sum()
    print(f"{column}: Unique values = {unique_values}, Total rows = {total_rows}, Null values = {null_values}")
    if unique_values == total_rows and null_values == 0:
        print(f"--> {column} can be a primary key.\n")
    else:
        print(f"--> {column} cannot be a primary key.\n")

user_pseudo_id: Unique values = 638, Total rows = 1000, Null values = 0
--> user_pseudo_id cannot be a primary key.

event_timestamp: Unique values = 1000, Total rows = 1000, Null values = 0
--> event_timestamp can be a primary key.

event_bundle_sequence_id: Unique values = 1000, Total rows = 1000, Null values = 0
--> event_bundle_sequence_id can be a primary key.

In [266]:
# Creating a new DataFrame that contains only the columns required for platform usage analysis.
# We will include the 'event_date', 'user_pseudo_id', and 'platform' columns.
data=df
# Note: 'user_pseudo_id' is included for potential user-based platform usage analysis.
platform_usage_df = pd.DataFrame({
    'Event Date': data['event_date'],
    'User Pseudo ID': data['user_pseudo_id'],
    'Platform': data['platform']
})

platform_usage_df

     Event Date  User Pseudo ID Platform
0      20240123    1.803115e+09      WEB
1      20240123    1.370019e+09      WEB
2      20240123    2.091432e+09      WEB
3      20240123    1.821760e+09      WEB
4      20240123    1.665243e+09      WEB
..          ...             ...      ...
995    20240123    8.756038e+08      WEB
996    20240123    8.756038e+08      WEB
997    20240123    8.756038e+08      WEB
998    20240123    8.756038e+08      WEB
999    20240123    8.756038e+08      WEB

[1000 rows x 3 columns]

In [267]:
active_user_counts = data['is_active_user'].value_counts()
active_user_counts

is_active_user
True     948
False     52
Name: count, dtype: int64

In [268]:
# Creating a new DataFrame that contains only the columns required for the analysis of active users.
# We will include the 'event_date', 'user_pseudo_id', and 'is_active_user' columns.

# Note: Including 'platform' to potentially analyze active user behavior across different platforms.
active_users_df = pd.DataFrame({
    'event_date': data['event_date'],
    'user_pseudo_id': data['user_pseudo_id'],
    'is_active_user': data['is_active_user'],
    'event_timestamp': data['event_timestamp']
})

active_users_df.head()

   event_date  user_pseudo_id  is_active_user   event_timestamp
0    20240123    1.803115e+09            True  1706041021863308
1    20240123    1.370019e+09            True  1706043908464706
2    20240123    2.091432e+09            True  1706055327780748
3    20240123    1.821760e+09            True  1705989378681557
4    20240123    1.665243e+09            True  1706013824763773

In [269]:
active_users_df.to_csv('/Users/bhaskaradhikari/freelance/data/external/active_users_df.csv', index=False)

In [270]:
# Creating a new DataFrame with the specified columns for Traffic Sources and Campaign Effectiveness analysis
# Note: Direct extraction of detailed information from JSON columns (traffic_source, event_params, ecommerce) 
# is simplified due to previous execution issues. 

# Simplified DataFrame creation with general user and event information
traffic_campaigns_simplified_df = pd.DataFrame({
    'Event Date': data['event_date'],
    'User Pseudo ID': data['user_pseudo_id'],
    'Platform': data['platform'],
    'Is Active User': data['is_active_user'],
    # Placeholder columns for extracted data, assuming extraction will be performed later or outside this environment
    'Campaign Name (Placeholder)': 'To be extracted',
    'Event Value USD (Placeholder)': data['event_value_in_usd'].fillna(0),
    # Additional placeholders for traffic source and event parameters extraction
    'Traffic Source Details (Placeholder)': 'To be extracted',
    'User Engagement/Conversion Details (Placeholder)': 'To be extracted'
})

traffic_campaigns_simplified_df.head()

,Event Date,User Pseudo ID,Platform,Is Active User,Campaign Name (Placeholder),Event Value USD (Placeholder),Traffic Source Details (Placeholder),User Engagement/Conversion Details (Placeholder)
0,20240123,1.803115e+09,WEB,True,To be extracted,0.0,To be extracted,To be extracted
1,20240123,1.370019e+09,WEB,True,To be extracted,0.0,To be extracted,To be extracted
2,20240123,2.091432e+09,WEB,True,To be extracted,0.0,To be extracted,To be extracted
3,20240123,1.821760e+09,WEB,True,To be extracted,0.0,To be extracted,To be extracted
4,20240123,1.665243e+09,WEB,True,To be extracted,0.0,To be extracted,To be extracted

In [271]:
df[['event_date','user_pseudo_id','traffic_source',
    'event_params','ecommerce','is_active_user','event_timestamp',
    ]]

,event_date,user_pseudo_id,traffic_source,event_params,ecommerce,is_active_user,event_timestamp
0,20240123,1.803115e+09,"{\n ""traffic_source"": {\n ""name"": ""(direct...","{\n ""event_params"": [{\n ""key"": ""batch_ord...","{\n ""ecommerce"": null\n}",True,1706041021863308
1,20240123,1.370019e+09,"{\n ""traffic_source"": {\n ""name"": ""(referr...","{\n ""event_params"": [{\n ""key"": ""campaign""...","{\n ""ecommerce"": null\n}",True,1706043908464706
2,20240123,2.091432e+09,"{\n ""traffic_source"": {\n ""name"": ""TNT_DPA...","{\n ""event_params"": [{\n ""key"": ""source"",\...","{\n ""ecommerce"": null\n}",True,1706055327780748
3,20240123,1.821760e+09,"{\n ""traffic_source"": {\n ""name"": ""TNT_Car...","{\n ""event_params"": [{\n ""key"": ""medium"",\...","{\n ""ecommerce"": null\n}",True,1705989378681557
4,20240123,1.665243e+09,"{\n ""traffic_source"": {\n ""name"": ""TNT_Car...","{\n ""event_params"": [{\n ""key"": ""entrances...","{\n ""ecommerce"": null\n}",True,1706013824763773
...,...,...,...,...,...,...,...
995,20240123,8.756038e+08,"{\n ""traffic_source"": {\n ""name"": ""TNT_Car...","{\n ""event_params"": [{\n ""key"": ""page_loca...","{\n ""ecommerce"": null\n}",True,1706059367359036
996,20240123,8.756038e+08,"{\n ""traffic_source"": {\n ""name"": ""TNT_Car...","{\n ""event_params"": [{\n ""key"": ""ignore_re...","{\n ""ecommerce"": null\n}",True,1706059418688359
997,20240123,8.756038e+08,"{\n ""traffic_source"": {\n ""name"": ""TNT_Car...","{\n ""event_params"": [{\n ""key"": ""batch_pag...","{\n ""ecommerce"": null\n}",True,1706059422947325
998,20240123,8.756038e+08,"{\n ""traffic_source"": {\n ""name"": ""TNT_Car...","{\n ""event_params"": [{\n ""key"": ""session_e...","{\n ""ecommerce"": null\n}",True,1706059426919338
999,20240123,8.756038e+08,"{\n ""traffic_source"": {\n ""name"": ""TNT_Car...","{\n ""event_params"": [{\n ""key"": ""batch_pag...","{\n ""ecommerce"": null\n}",True,1706059435947378

In [272]:
import json
import pandas as pd

# Open the JSON file and load its contents
with open('/Users/bhaskaradhikari/freelance/data/raw/bquxjob_423dc57a_18d43302074.json', 'r') as file:
    data = json.load(file)

# Extract the required fields from each object in the array
rows = []
for obj in data:
    event_date = obj['event_date']
    user_pseudo_id = obj['user_pseudo_id']
    city = obj['geo']['city']
    country = obj['geo']['country']
    event_timestamp = obj['event_timestamp']

    rows.append({'event_date': event_date, 
                 'user_pseudo_id': user_pseudo_id, 
                 'city': city, 
                 'country': country, 
                 'event_timestamp': event_timestamp})

# Put the extracted rows in a pandas DataFrame
df = pd.DataFrame(rows)

# Print the resulting DataFrame
df

,event_date,user_pseudo_id,city,country,event_timestamp
0,20240123,1803115498.1706041017,Columbia,United States,1706041021863308
1,20240123,1370019237.1706043908,Seattle,United States,1706043908464706
2,20240123,2091431952.1706055328,,United States,1706055327780748
3,20240123,1821760332.1705989378,Cypress,United States,1705989378681557
4,20240123,1665243307.1706013825,Lowell,United States,1706013824763773
...,...,...,...,...,...
995,20240123,875603768.1706059327,Midland,United States,1706059367359036
996,20240123,875603768.1706059327,Midland,United States,1706059418688359
997,20240123,875603768.1706059327,Midland,United States,1706059422947325
998,20240123,875603768.1706059327,Midland,United States,1706059426919338
999,20240123,875603768.1706059327,Midland,United States,1706059435947378

In [273]:
df.to_csv('/Users/bhaskaradhikari/freelance/data/external/geo_insights_df.csv', index=False)

In [274]:
import json
import pandas as pd

# Open the JSON file and load its contents
with open('/Users/bhaskaradhikari/freelance/data/raw/bquxjob_423dc57a_18d43302074.json', 'r') as file:
    data = json.load(file)

# Extract the required fields from each object in the array
rows = []
for obj in data:
    event_date = obj['event_date']
    user_pseudo_id = obj['user_pseudo_id']
    traffic_source_name = obj['traffic_source']['name']
    traffic_source_medium = obj['traffic_source']['medium']
    traffic_source_source = obj['traffic_source']['source']
    event_timestamp = obj['event_timestamp']


    rows.append({'event_date': event_date, 'user_pseudo_id': user_pseudo_id, 
                 'traffic_source_name': traffic_source_name, 'traffic_source_medium': traffic_source_medium ,
                 'traffic_source_source': traffic_source_source,
                 'event_timestamp': event_timestamp})

# Put the extracted rows in a pandas DataFrame
df = pd.DataFrame(rows)

# Print the resulting DataFrame
df

,event_date,user_pseudo_id,traffic_source_name,traffic_source_medium,traffic_source_source,event_timestamp
0,20240123,1803115498.1706041017,(direct),(none),(direct),1706041021863308
1,20240123,1370019237.1706043908,(referral),referral,m.facebook.com,1706043908464706
2,20240123,2091431952.1706055328,TNT_DPA - Interest - Prospecting,cpc,facebook,1706055327780748
3,20240123,1821760332.1705989378,TNT_Carousel/Image - Shopping - Retargeting,cpc,facebook,1705989378681557
4,20240123,1665243307.1706013825,TNT_Carousel/Image - Shopping - Retargeting,cpc,facebook,1706013824763773
...,...,...,...,...,...,...
995,20240123,875603768.1706059327,TNT_Carousel/Image - Shopping - Prospecting,cpc,facebook,1706059367359036
996,20240123,875603768.1706059327,TNT_Carousel/Image - Shopping - Prospecting,cpc,facebook,1706059418688359
997,20240123,875603768.1706059327,TNT_Carousel/Image - Shopping - Prospecting,cpc,facebook,1706059422947325
998,20240123,875603768.1706059327,TNT_Carousel/Image - Shopping - Prospecting,cpc,facebook,1706059426919338
999,20240123,875603768.1706059327,TNT_Carousel/Image - Shopping - Prospecting,cpc,facebook,1706059435947378

In [275]:
df.to_csv('/Users/bhaskaradhikari/freelance/data/external/traffic_sources.csv', index=False)

In [276]:
import json
import pandas as pd

# Read the JSON file
with open('/Users/bhaskaradhikari/freelance/data/raw/bquxjob_423dc57a_18d43302074.json', 'r') as file:
    data = json.load(file)

# Extract the required fields
df = pd.DataFrame([{
    'event_date': event['event_date'],
    'user_pseudo_id': event['user_pseudo_id'],
    'page_title': next((param['value']['string_value'] for param in event['event_params'] if param['key'] == 'page_title'), None),
    'page_location': next((param['value']['string_value'] for param in event['event_params'] if param['key'] == 'page_location'), None),
    'page_referrer': next((param['value']['string_value'] for param in event['event_params'] if param['key'] == 'page_referrer'), None),
    'event_timestamp': event['event_timestamp']
} for event in data])

# Print the DataFrame
df

,event_date,user_pseudo_id,page_title,page_location,page_referrer,event_timestamp
0,20240123,1803115498.1706041017,Multiple Part Numbers Search | P.com,https://www.p.com/search-list,https://www.p.com/catalog-product/collection/4...,1706041021863308
1,20240123,1370019237.1706043908,"Polaris 5133428 - Nut, Axle | P.com",https://www.p.com/product/polaris/5133428?ref=...,http://m.facebook.com/,1706043908464706
2,20240123,2091431952.1706055328,Rock-A-Billy Front/Rear Tires | P.com,https://www.p.com/catalog-product/collection/0...,http://m.facebook.com/,1706055327780748
3,20240123,1821760332.1705989378,"Honda 11330-MFJ-A40 - COVER, R. | P.com",https://www.p.com/product/honda/11330-MFJ-A40?...,None,1705989378681557
4,20240123,1665243307.1706013825,"P: OEM Motorcycle Parts, ATV Parts, Marine Parts",https://www.p.com/?utm_source=facebook&utm_med...,http://m.facebook.com/,1706013824763773
...,...,...,...,...,...,...
995,20240123,875603768.1706059327,Yamaha ATV 2023 OEM Parts Diagram for Graphics...,https://www.p.com/catalog/yamaha/atv/2023/yfz4...,https://www.p.com/catalog/yamaha/atv/2023/yfz4...,1706059367359036
996,20240123,875603768.1706059327,Yamaha ATV Parts | P.com,https://www.p.com/catalog/yamaha/atv,https://www.p.com/catalog/yamaha?utm_source=fa...,1706059418688359
997,20240123,875603768.1706059327,Yamaha ATV 2023 OEM Parts Diagram for Graphics...,https://www.p.com/catalog/yamaha/atv/2023/yfz4...,https://www.p.com/catalog/yamaha/atv/2023/yfz4...,1706059422947325
998,20240123,875603768.1706059327,Yamaha ATV 2023 OEM Parts Diagram for Graphics...,https://www.p.com/catalog/yamaha/atv/2023/yfz4...,https://www.p.com/catalog/yamaha/atv/2023/yfz4...,1706059426919338
999,20240123,875603768.1706059327,Yamaha ATV 2023 OEM Parts Diagram for Rear Arm...,https://www.p.com/catalog/yamaha/atv/2023/yfz4...,https://www.p.com/catalog/yamaha/atv/2023/yfz4...,1706059435947378

In [277]:
df.to_csv('/Users/bhaskaradhikari/freelance/data/external/event_params.csv', index=False)